name: final_project
description: "A real-time campus engagement app."
# publish_to: 'none'  Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure compatibility with recent Flutter/Dart versions

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  geolocator: ^14.0.0
  get_it: ^8.0.3 # You might not need get_it anymore if fully migrating to Riverpod
  go_router: ^15.1.2
  http: ^1.3.0
  image_picker: ^1.1.1
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1 # ENSURE THIS IS PRESENT AND UP-TO-DATE
  firebase_crashlytics: ^4.3.5
  sqflite: ^2.3.2 # Added for SQLite
  path_provider: ^2.1.3 # Added for SQLite
  path: ^1.9.0 # Added for SQLite
  rxdart: ^0.27.7 # Added for LeaderboardProvider stream.startWith
  flutter_local_notifications: ^17.0.0 # For local notifications
  flutter_background_service: ^5.0.0 # Added for persistent background tasks
  web_socket_channel: ^2.4.0 # Added for real-time WebSocket connections

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Recommended lints for good coding practices

  # Code generation for JSON serialization (if you use json_serializable later)
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/
  #   - assets/fonts/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #   - fonts:
  #     - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #       style: italic
  #   - family: Trajan Pro
  #   - fonts:
  #     - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
