name: final_project
description: "A real-time campus engagement app."
# publish_to: 'none'  Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure compatibility with recent Flutter/Dart versions

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 # For managing application state
  go_router: ^14.0.0 # A declarative routing package for Flutter
  shared_preferences: ^2.2.3 # For simple key-value storage (e.g., auth tokens, theme preference)
  firebase_core: ^3.1.0 # Firebase core plugin
  firebase_auth: ^5.1.0 # Firebase Authentication plugin
  firebase_messaging: ^15.0.1 # Firebase Cloud Messaging plugin
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1 # Functional programming in Dart
  get_it: ^7.6.7 # Add the get_it dependency here (use the latest version)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Recommended lints for good coding practices
  # Code generation for JSON serialization (if you use json_serializable later)
  # build_runner: ^2.4.9
  # json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/
  #   - assets/fonts/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package